### ISSUE TITLE
Le bouton "Voir les emails envoyés" dans l'interface admin

### ISSUE THREAD

**Issue by navidemad** [hostolab/covidliste#478]
## Contexte / Problème

Dans l'interface admin > Outils support > Volontaires
Si vous cherchez un utilisateur par son email, les résultats en dessous devrait avoir un bouton "Voir les emails envoyés".
Au clic de ce bouton, en environnement de developement j'ai l'erreur suivant, surement car on a pas de clef API en dev, mais peut-être un moyen de prévenir cela ?

```
Started GET "/admin/users?user%5Bemail%5D=[FILTERED]&other%5Bwith_mails%5D=&commit=Voir+les+emails+envoy%C3%A9s" for 127.0.0.1 at 2021-04-17 22:56:26 +0200
  User Load (1.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  Role Load (1.1ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 2]]
  ↳ app/models/user.rb:82:in `admin?'
Processing by Admin::UsersController#index as HTML
  Parameters: {"user"=>{"email"=>"[FILTERED]"}, "other"=>{"with_mails"=>""}, "commit"=>"Voir les emails envoyés"}
  CACHE Role Load (0.1ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 2]]
  ↳ app/models/user.rb:82:in `admin?'
  CACHE Role Load (0.1ms)  SELECT "roles".* FROM "roles" INNER JOIN "users_roles" ON "roles"."id" = "users_roles"."role_id" WHERE "users_roles"."user_id" = $1 AND (((roles.name = 'admin') AND (roles.resource_type IS NULL) AND (roles.resource_id IS NULL)))  [["user_id", 2]]
  ↳ app/models/user.rb:82:in `admin?'
  User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."email_bidx" = $1 LIMIT $2  [["email_bidx", "EkWTap2ezkUm+X/dIVAPGRWxpy5+tsZh3LdvtpuuKVI="], ["LIMIT", 1]]
  ↳ app/controllers/admin/users_controller.rb:7:in `index'
{:limit=>50, :offset=>0, :days=>30, :email=>"navid.emad@yespark.fr", :sort=>"desc"}
ETHON: Libcurl initialized
ETHON: performed EASY effective_url=https://api.sendinblue.com/v3/smtp/statistics/events?limit=50&offset=0&days=30&email=navid.emad%40yespark.fr&sort=desc response_code=401 return_code=ok total_time=0.143314
Completed 500 Internal Server Error in 172ms (ActiveRecord: 1.2ms | Allocations: 5060)

SibApiV3Sdk::ApiError - :
  app/services/mail_provider_service.rb:16:in `find_mails'
  app/controllers/admin/users_controller.rb:8:in `index'
```

## Priorité (Requis)

- `P3`: Pas prioritaire

**Comment by carsso** [comment]
Yep, il te faut un compte et une clé API si tu veux pouvoir l'utiliser en DEV :)

**Comment by navidemad** [comment]
Possible d'éventuellement retourner un array vide en cas d'absence de clef ? (je voulais voir en fait l'esthétique du rendu de la page)

**Comment by carsso** [comment]
Yep, clairement, ça serait super.

**Comment by carsso** [comment]
Encore mieux ce serait de renvoyer des infos fausses, qui sont identiques a celles renvoyées par l'API.
Si tu sais si on peut faire ça en rails de manière simple en fonction de l'env + de la présence de la clé ?

**Comment by navidemad** [comment]
Il y a les cassettes VCR qui sont des mocks des retours JSON utilisé en environnement de test quand on a affaire à des services API externes. Je vais voir si moyen d'utiliser ça en dev aussi. 🧐

**Comment by carsso** [comment]
Ouais, comme ça je choppe le retour de l'api, on en fait un mock et paf c'est good pour tous ceux qui bossent sur les interfaces pour check.
